#All containers are defined undersevices
services:
  web:
    build: .  # Build the image from current directory(.) using the Dockerfile.
    container_name: twitter-api
    ports:
      - "8000:8000"
    depends_on: # Ensures db and redis services start before web.
      - db
      - redis
    env_file:
      - .env
  
  db:
    image: postgres:14
    container_name: post_gress_db
    restart: always
    environment:
      POSTGRES_USER: reyhaneh
      POSTGRES_PASSWORD: ${mydbpass}
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:  # Volume is a special storage space outside your container's filesystem that Docker manages
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7
    container_name: redis-cache
    ports:
      - "6379:6379"

volumes:
  postgres_data:
